DTinker/discord-resources

README.md
will add more later eventually >.>
=> ok that should be good

README.md
- [mhmm ] I have added my package in alphabetical order
- [ yes] I know that this package was not listed before
- [ yes] I have added rawgit link to the repo and to my pull request
- [yes ] I have read [Contribution guidelines](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#contribution-guidelines).
=> updated the gif

README.md
https://github.com/bubbie/discord-old-profile
https://cdn.rawgit.com/bubbie/discord-old-profile/master/stylesheet.css
=> added my discord-old-profile

README.md
=> Adding chat button

README.md
=> Add a link to the project itself

README.md
=> Spacegray and Classic Embeds

README.md
- [o ] I have added my package in alphabetical order
- [w ] I know that this package was not listed before
- [o ] I have added rawgit link to the repo and to my pull request
- [- ] I have read [Contribution guidelines](https://github.com/beautiful-discord-community/resources/blob/master/CONTRIBUTING.md#contribution-guidelines).
=> avatar shadows

README.md
https://www.youtube.com/watch?v=MAW2lygZC_4
=> SPAAAAAACE!

README.md
=> DID I DO IT RIGHT?

README.md
=> add 80s-green-disc0rd

README.md
=> Added Jakeoid Remix of Discord Adapta

README.md
=> Fixed naming schemes :eyes:

README.md
Go easy on me, this is my first pull request ever.
I hope I did this right.
=> Adding my grain of salt to the cookie jar.

README.md
Sleepy kaos isnt a productive kaos
=> *facepalm*

.github/PULL_REQUEST_TEMPLATE.md, .travis.yml, CONTRIBUTING.md, LICENSE, README.md, repo_test.go, vendor/github.com/aymerick/douceur/css/declaration.go, vendor/github.com/aymerick/douceur/css/rule.go, vendor/github.com/aymerick/douceur/css/stylesheet.go, vendor/github.com/aymerick/douceur/parser/parser.go, vendor/github.com/aymerick/douceur/parser/parser_test.go
Adding support for css validation and some other things.
Big changes incoming bois~
=> Feature embed validation

README.md
=> no memes kthx

README.md
=> Added semi-monokai.css

README.md
- github.com repo: https://github.com/LewisTehMinerz/BootyfulDiscord
- embed url: https://cdn.rawgit.com/LewisTehMinerz/BootyfulDiscord/master/BootyfulDiscord.theme.css
=> add my theme

README.md
=> Added my own css to the list

README.md
=> Add transparent base snippet

README.md
=> Fixed URL to Discord_MaterialTheme | Embed

README.md
=> Added Discord-Prism

README.md
=> Add `no-white-theme.css`

README.md
=> Updated info to my theme

README.md
=> Forgot to change theme name..

README.md
=> Updated screenshots

README.md
=> More previews on my theme

README.md
Because the world needs a bit more pink
I have read and followed the contribution guidelines.
=> Add pink-hljs

README.md
=> Adding theme

README.md
=> Fix pink-hljs preview

README.md
=> Fixed repo link

README.md
=> New screenshots to AlexFlipnote/Discord_Theme

README.md
=> New screenshot on preview 4

README.md
- github.com repo: https://github.com/Oliyy/Material-Design-Discord
- embed url: https://rawgit.com/Oliyy/Material-Design-Discord/master/theme.css
=> Add Material-Design-Discord to Theme List

README.md
=> Fixed my own screenshots.. again .-.

README.md
=> Added another screenshot for Discord-Fade-Anims

README.md
=> Update preview link

README.md
=> Added my Custom Nametags under Useful Snippets

README.md
=> quick mock for new readme
